[versions]
# App
appVersionName = "0.1.0"
appVersionCode = "1"
compileSdk = "36"
targetSdk = "36"
minSdk = "26"

# Toolchain
agp = "9.2.0"
kotlin = "2.3.10"

# Libraries
androidxCore = "1.17.0"
androidxActivity = "1.12.4"
androidxLifecycle = "2.10.0"
composeBom = "2025.10.01"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

[bundles]
compose = [
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-material3",
    "compose-material-icons-extended",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
